RECOMMENDER_METHOD_SAMPLING = "SAMPLING"
RECOMMENDER_METHOD_HIGHEST_WEIGHT = "HIGHEST_WEIGHT"

PARSE_TYPE_PARSE = 'parse'
PARSE_TYPE_NGRAMS = 'ngrams'
ORACLE_TYPE_CUSTOM_WEIGHT = 'CUSTOM_WEIGHT'
ORACLE_TYPE_TOP_N = 'top_n'
ORACLE_TYPE_KEEPTRACK = 'keeptrack'
ORACLE_TYPE_ACTIVE_LEARNING = 'active_learning'
ORACLE_TYPE_ACTIVE_LEARNING2 = 'active_learning2'
ORACLE_TYPE_ILP_FEEDBACK = "ilp_feedback"
ORACLE_TYPE_ACCEPT_REJECT = 'accept_reject'
ORACLE_TYPE_ACCEPT = 'accept'
ORACLE_TYPE_REJECT = 'reject'
ORACLE_TYPE_ACCEPT_ALL = 'accept_all'
ORACLE_TYPE_REJECT_ALL = 'reject_all'

CHANGE_WEIGHT_MODE_ACCEPT = 'accept'
CHANGE_WEIGHT_MODE_REJECT = 'reject'
CHANGE_WEIGHT_MODE_IMPLICIT_REJECT = 'implicit_reject'
