export const LOAD_USER_ASSIGNMENTS_REQUEST = "LOAD_USER_ASSIGNMENTS_REQUEST";
export const LOAD_USER_ASSIGNMENTS_SUCCESS = "LOAD_USER_ASSIGNMENTS_SUCCESS";
export const LOAD_USER_ASSIGNMENTS_FAIL    = "LOAD_USER_ASSIGNMENTS_FAIL";
export const LOAD_USER_ASSIGNMENTS_RESET = "LOAD_USER_ASSIGNMENTS_RESET";
export const PATCH_ASSIGNMENT_REQUEST = "PATCH_ASSIGNMENT_REQUEST";
export const PATCH_ASSIGNMENT_SUCCESS = "PATCH_ASSIGNMENT_SUCCESS";
export const PATCH_ASSIGNMENT_FAIL = "PATCH_ASSIGNMENT_FAIL";
