TIME = 't'
SCORE = 'score'
DATASET = 'dataset'
VERSION = 'algorithm version ='
ITERATIONS = 'max iteration count ='
TOPIC = 'topic'
ORACLE_TYPE = 'oracle_type'
SUMMARY_LEN = 'L ='
MAX_WEIGHT = 'TODO'
