export const LOAD_ASSIGNMENT_TEMPLATE_REQUEST = "LOAD_ASSIGNMENT_TEMPLATE_REQUEST";
export const LOAD_ASSIGNMENT_TEMPLATE_SUCCESS = "LOAD_ASSIGNMENT_TEMPLATE_SUCCESS";
export const LOAD_ASSIGNMENT_TEMPLATE_FAIL    = "LOAD_ASSIGNMENT_TEMPLATE_FAIL";

export const LOAD_ASSIGNMENT_TEMPLATES_REQUEST = "LOAD_ASSIGNMENT_TEMPLATES_REQUEST";
export const LOAD_ASSIGNMENT_TEMPLATES_SUCCESS = "LOAD_ASSIGNMENT_TEMPLATES_SUCCESS";
export const LOAD_ASSIGNMENT_TEMPLATES_FAIL    = "LOAD_ASSIGNMENT_TEMPLATES_FAIL";
