/**
 * Created by hatieke on 2017-06-14.
 */

export const USER_ACCEPT_ASSIGNMENT_REQUEST = "USER_ACCEPT_ASSIGNMENT_REQUEST";
export const USER_ACCEPT_ASSIGNMENT_SUCCESS = "USER_ACCEPT_ASSIGNMENT_SUCCESS";
export const USER_ACCEPT_ASSIGNMENT_FAIL = "USER_ACCEPT_ASSIGNMENT_FAIL";
export const USER_LOAD_ACTIVE_ASSIGNMENT_REQUEST = "USER_LOAD_ACTIVE_ASSIGNMENT_REQUEST";
export const USER_LOAD_ACTIVE_ASSIGNMENT_SUCCESS = "USER_LOAD_ACTIVE_ASSIGNMENT_SUCCESS";
export const USER_LOAD_ACTIVE_ASSIGNMENT_FAIL    = "USER_LOAD_ACTIVE_ASSIGNMENT_FAIL";
