/**
 * Created by hatieke on 2017-06-18.
 */
export const RESET_STORE = "RESET_STORE";
export const SUMMARY_LOAD_REQUEST   =  "SUMMARY_LOAD_REQUEST";
export const SUMMARY_LOAD_SUCCESS   =  "SUMMARY_LOAD_SUCCESS";
export const SUMMARY_LOAD_FAIL      =  "SUMMARY_LOAD_FAIL";
export const RECOMMENDATION_LOAD_REQUEST   =  "RECOMMENDATION_LOAD_REQUEST";
export const RECOMMENDATION_LOAD_SUCCESS   =  "RECOMMENDATION_LOAD_SUCCESS";
export const RECOMMENDATION_LOAD_FAIL      =  "RECOMMENDATION_LOAD_FAIL";
